### ISSUE TITLE
Side bar does not flow on tighter windows

### ISSUE THREAD

**Issue by kennyballou** [xxdesmus/nslarchive.org#1]
Attached image shows problem with floating contact buttons.  Screen resolution of Firefox 52.4.0 is roughly 1145 x 1000.

![2017-12-19-141738_1141x997_scrot](https://user-images.githubusercontent.com/2186188/34179264-715d3494-e4c7-11e7-9ceb-7343a64f494b.png)

**Comment by xxdesmus** [comment]
Thanks for the report. I’ll look into fixing this.

**Comment by xxdesmus** [comment]
I think https://github.com/xxdesmus/nslarchive.org/commit/312edd3726202de9222bf6e066604a54b9a8ed51  should fix this. Thanks for reporting!

**Comment by kennyballou** [comment]
👍 Looks fixed indeed. Thank you.
